model:
  type: xgb_ensemble        # options: "gp", "xgb_ensemble"

target_column: charge_capacity_mAh_g
maximize: true
ei_xi: 0.01

# Number of experiment suggestions per batch (align with lab workflow, e.g. 3–10)
suggestions_per_batch: 5

# Initial DOE size (~20–40, or 3–4x dimension)
initial_doe_samples: 30

# random candidates to evaluate acquisition on
candidate_pool_size: 10000

parameters:
  - {name: P1, low: 0.5, high: 1.5, type: float}
  - {name: N1, low: 20,  high: 80,  type: int}
  - {name: t1, low: 0.5, high: 2.0, type: float}
  - {name: P2, low: 1.5, high: 3.5, type: float}
  - {name: N2, low: 10,  high: 50,  type: int}
  - {name: t2, low: 1.0, high: 4.0, type: float}
  - {name: P3, low: 3.0, high: 5.0, type: float}
  - {name: N3, low: 2,   high: 15,  type: int}
  - {name: t3, low: 2.0, high: 8.0, type: float}
  

# top 20% performing parameters from initial data
# parameters:
#   - {name: P1, low: 0.58, high: 0.97, type: float}
#   - {name: P2, low: 1.98, high: 2.53, type: float}
#   - {name: N2, low: 20,  high: 30, type: int}

#   # These will be treated as constants in sampling
#   - {name: N1, low: 60, high: 60, type: int}
#   - {name: t1, low: 1.0, high: 1.0, type: float}
#   - {name: t2, low: 2.0, high: 2.0, type: float}
#   - {name: P3, low: 4.0, high: 4.0, type: float}
#   - {name: N3, low: 5,   high: 5,   type: int}
#   - {name: t3, low: 4.0, high: 4.0, type: float}

# Vary Stage 1 (Stage 2 & 3 fixed)
# parameters:
#   - {name: P1, low: 0.5, high: 1.5, type: float}
#   - {name: N1, low: 20,  high: 80,  type: int}
#   - {name: t1, low: 0.5, high: 2.0, type: float}

#   - {name: P2, low: 2.5, high: 2.5, type: float}  # fixed
#   - {name: N2, low: 30,  high: 30,  type: int}    # fixed
#   - {name: t2, low: 2.0, high: 2.0, type: float}  # fixed

#   - {name: P3, low: 4.0, high: 4.0, type: float}  # fixed
#   - {name: N3, low: 5,   high: 5,   type: int}    # fixed
#   - {name: t3, low: 4.0, high: 4.0, type: float}  # fixed


# Vary Stage 2 (Stage 1 & 3 fixed)
# parameters:
#   - {name: P1, low: 0.8, high: 0.8, type: float}  # fixed
#   - {name: N1, low: 60,  high: 60,  type: int}    # fixed
#   - {name: t1, low: 1.0, high: 1.0, type: float}  # fixed

#   - {name: P2, low: 1.5, high: 3.5, type: float}
#   - {name: N2, low: 10,  high: 50,  type: int}
#   - {name: t2, low: 1.0, high: 4.0, type: float}

#   - {name: P3, low: 4.0, high: 4.0, type: float}  # fixed
#   - {name: N3, low: 5,   high: 5,   type: int}    # fixed
#   - {name: t3, low: 4.0, high: 4.0, type: float}  # fixed

# # Vary Stage 3 (Stage 1 & 2 fixed)
# parameters:
#   - {name: P1, low: 0.8, high: 0.8, type: float}  # fixed
#   - {name: N1, low: 60,  high: 60,  type: int}    # fixed
#   - {name: t1, low: 1.0, high: 1.0, type: float}  # fixed

#   - {name: P2, low: 2.5, high: 2.5, type: float}  # fixed
#   - {name: N2, low: 30,  high: 30,  type: int}    # fixed
#   - {name: t2, low: 2.0, high: 2.0, type: float}  # fixed

#   - {name: P3, low: 3.0, high: 5.0, type: float}
#   - {name: N3, low: 2,   high: 15,  type: int}
#   - {name: t3, low: 2.0, high: 8.0, type: float}

 
